services:
  ogvjscompiler:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "no"
    volumes:
      - type: bind
        source: .
        target: /ogv.js
    working_dir: /ogv.js
    entrypoint:  ["make"]
